# docker-compose.yml

version: '3.8'

services:
  heatmap-bot:
    # Build the Docker image using the Dockerfile in the current directory
    build: .
    
    # Load environment variables from the .env file
    # This is how you pass secrets to the container locally
    env_file:
      - .env
      
    # Map port 8080 on your local machine to port 8000 inside the container
    # You can then access the health check at http://localhost:8080/health
    ports:
      - "8080:8000"
      
    # Mount local directories into the container
    # This allows for live code reloading without rebuilding the image.
    # Any change in bot.py will be reflected after restarting the container.
    volumes:
      - .:/app
      - /app/logs # Persist logs outside the container's ephemeral filesystem
